image: node:v14.17.0

cache:
  paths: 
    -node_modules/

stages: 
  -install
  -deploy

Install: 
  stage: install
  script: 
    -yarn install

Production: 
  image: ruby:latest
  only:
    -main
  stage: deploy
  script: 
    - app-get update -qy
    - app-get install -y ruby-dev
    - gem install dpl
    - dpl --provider=heroku --
app=$HEROKU_APP_NAME --api-key=$HEROKU_API_KEY